// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Magazinep.proto

package services;

public final class Magazinep {
  private Magazinep() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code services.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>EXIST = 0;</code>
     */
    EXIST(0),
    /**
     * <code>BORROWED = 1;</code>
     */
    BORROWED(1),
    /**
     * <code>RETURNED = 2;</code>
     */
    RETURNED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>EXIST = 0;</code>
     */
    public static final int EXIST_VALUE = 0;
    /**
     * <code>BORROWED = 1;</code>
     */
    public static final int BORROWED_VALUE = 1;
    /**
     * <code>RETURNED = 2;</code>
     */
    public static final int RETURNED_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Status forNumber(int value) {
      switch (value) {
        case 0: return EXIST;
        case 1: return BORROWED;
        case 2: return RETURNED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return services.Magazinep.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:services.Status)
  }

  /**
   * Protobuf enum {@code services.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MAGAZINE = 0;</code>
     */
    MAGAZINE(0),
    /**
     * <code>BOOK = 1;</code>
     */
    BOOK(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MAGAZINE = 0;</code>
     */
    public static final int MAGAZINE_VALUE = 0;
    /**
     * <code>BOOK = 1;</code>
     */
    public static final int BOOK_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return MAGAZINE;
        case 1: return BOOK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return services.Magazinep.getDescriptor().getEnumTypes().get(1);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:services.Type)
  }

  /**
   * Protobuf enum {@code services.RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NONE = 0;</code>
     */
    NONE(0),
    /**
     * <code>BORROW = 1;</code>
     */
    BORROW(1),
    /**
     * <code>RETURN = 2;</code>
     */
    RETURN(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NONE = 0;</code>
     */
    public static final int NONE_VALUE = 0;
    /**
     * <code>BORROW = 1;</code>
     */
    public static final int BORROW_VALUE = 1;
    /**
     * <code>RETURN = 2;</code>
     */
    public static final int RETURN_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return NONE;
        case 1: return BORROW;
        case 2: return RETURN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return services.Magazinep.getDescriptor().getEnumTypes().get(2);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:services.RequestType)
  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:services.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code services.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:services.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return services.Magazinep.internal_static_services_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return services.Magazinep.internal_static_services_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              services.Magazinep.User.class, services.Magazinep.User.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof services.Magazinep.User)) {
        return super.equals(obj);
      }
      services.Magazinep.User other = (services.Magazinep.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static services.Magazinep.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static services.Magazinep.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static services.Magazinep.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static services.Magazinep.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static services.Magazinep.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static services.Magazinep.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static services.Magazinep.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static services.Magazinep.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static services.Magazinep.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static services.Magazinep.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static services.Magazinep.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static services.Magazinep.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(services.Magazinep.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code services.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:services.User)
        services.Magazinep.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return services.Magazinep.internal_static_services_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return services.Magazinep.internal_static_services_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                services.Magazinep.User.class, services.Magazinep.User.Builder.class);
      }

      // Construct using services.Magazinep.User.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return services.Magazinep.internal_static_services_User_descriptor;
      }

      @java.lang.Override
      public services.Magazinep.User getDefaultInstanceForType() {
        return services.Magazinep.User.getDefaultInstance();
      }

      @java.lang.Override
      public services.Magazinep.User build() {
        services.Magazinep.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public services.Magazinep.User buildPartial() {
        services.Magazinep.User result = new services.Magazinep.User(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(services.Magazinep.User result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof services.Magazinep.User) {
          return mergeFrom((services.Magazinep.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(services.Magazinep.User other) {
        if (other == services.Magazinep.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:services.User)
    }

    // @@protoc_insertion_point(class_scope:services.User)
    private static final services.Magazinep.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new services.Magazinep.User();
    }

    public static services.Magazinep.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public services.Magazinep.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MagazineOrBuilder extends
      // @@protoc_insertion_point(interface_extends:services.Magazine)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string author = 2;</code>
     * @return The author.
     */
    java.lang.String getAuthor();
    /**
     * <code>string author = 2;</code>
     * @return The bytes for author.
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>.google.protobuf.Timestamp borrowed = 3;</code>
     * @return Whether the borrowed field is set.
     */
    boolean hasBorrowed();
    /**
     * <code>.google.protobuf.Timestamp borrowed = 3;</code>
     * @return The borrowed.
     */
    com.google.protobuf.Timestamp getBorrowed();
    /**
     * <code>.google.protobuf.Timestamp borrowed = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getBorrowedOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp returned = 4;</code>
     * @return Whether the returned field is set.
     */
    boolean hasReturned();
    /**
     * <code>.google.protobuf.Timestamp returned = 4;</code>
     * @return The returned.
     */
    com.google.protobuf.Timestamp getReturned();
    /**
     * <code>.google.protobuf.Timestamp returned = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getReturnedOrBuilder();

    /**
     * <code>.services.Status status = 5;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.services.Status status = 5;</code>
     * @return The status.
     */
    services.Magazinep.Status getStatus();

    /**
     * <code>.services.Type type = 6;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.services.Type type = 6;</code>
     * @return The type.
     */
    services.Magazinep.Type getType();

    /**
     * <code>.services.RequestType request_type = 7;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    int getRequestTypeValue();
    /**
     * <code>.services.RequestType request_type = 7;</code>
     * @return The requestType.
     */
    services.Magazinep.RequestType getRequestType();

    /**
     * <code>repeated .services.User observers = 8;</code>
     */
    java.util.List<services.Magazinep.User> 
        getObserversList();
    /**
     * <code>repeated .services.User observers = 8;</code>
     */
    services.Magazinep.User getObservers(int index);
    /**
     * <code>repeated .services.User observers = 8;</code>
     */
    int getObserversCount();
    /**
     * <code>repeated .services.User observers = 8;</code>
     */
    java.util.List<? extends services.Magazinep.UserOrBuilder> 
        getObserversOrBuilderList();
    /**
     * <code>repeated .services.User observers = 8;</code>
     */
    services.Magazinep.UserOrBuilder getObserversOrBuilder(
        int index);

    /**
     * <code>string genre = 9;</code>
     * @return The genre.
     */
    java.lang.String getGenre();
    /**
     * <code>string genre = 9;</code>
     * @return The bytes for genre.
     */
    com.google.protobuf.ByteString
        getGenreBytes();
  }
  /**
   * Protobuf type {@code services.Magazine}
   */
  public static final class Magazine extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:services.Magazine)
      MagazineOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Magazine.newBuilder() to construct.
    private Magazine(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Magazine() {
      title_ = "";
      author_ = "";
      status_ = 0;
      type_ = 0;
      requestType_ = 0;
      observers_ = java.util.Collections.emptyList();
      genre_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Magazine();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return services.Magazinep.internal_static_services_Magazine_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return services.Magazinep.internal_static_services_Magazine_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              services.Magazinep.Magazine.class, services.Magazinep.Magazine.Builder.class);
    }

    public static final int TITLE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object title_ = "";
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHOR_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object author_ = "";
    /**
     * <code>string author = 2;</code>
     * @return The author.
     */
    @java.lang.Override
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        author_ = s;
        return s;
      }
    }
    /**
     * <code>string author = 2;</code>
     * @return The bytes for author.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BORROWED_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp borrowed_;
    /**
     * <code>.google.protobuf.Timestamp borrowed = 3;</code>
     * @return Whether the borrowed field is set.
     */
    @java.lang.Override
    public boolean hasBorrowed() {
      return borrowed_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp borrowed = 3;</code>
     * @return The borrowed.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getBorrowed() {
      return borrowed_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : borrowed_;
    }
    /**
     * <code>.google.protobuf.Timestamp borrowed = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getBorrowedOrBuilder() {
      return borrowed_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : borrowed_;
    }

    public static final int RETURNED_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp returned_;
    /**
     * <code>.google.protobuf.Timestamp returned = 4;</code>
     * @return Whether the returned field is set.
     */
    @java.lang.Override
    public boolean hasReturned() {
      return returned_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp returned = 4;</code>
     * @return The returned.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getReturned() {
      return returned_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : returned_;
    }
    /**
     * <code>.google.protobuf.Timestamp returned = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getReturnedOrBuilder() {
      return returned_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : returned_;
    }

    public static final int STATUS_FIELD_NUMBER = 5;
    private int status_ = 0;
    /**
     * <code>.services.Status status = 5;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.services.Status status = 5;</code>
     * @return The status.
     */
    @java.lang.Override public services.Magazinep.Status getStatus() {
      services.Magazinep.Status result = services.Magazinep.Status.forNumber(status_);
      return result == null ? services.Magazinep.Status.UNRECOGNIZED : result;
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_ = 0;
    /**
     * <code>.services.Type type = 6;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.services.Type type = 6;</code>
     * @return The type.
     */
    @java.lang.Override public services.Magazinep.Type getType() {
      services.Magazinep.Type result = services.Magazinep.Type.forNumber(type_);
      return result == null ? services.Magazinep.Type.UNRECOGNIZED : result;
    }

    public static final int REQUEST_TYPE_FIELD_NUMBER = 7;
    private int requestType_ = 0;
    /**
     * <code>.services.RequestType request_type = 7;</code>
     * @return The enum numeric value on the wire for requestType.
     */
    @java.lang.Override public int getRequestTypeValue() {
      return requestType_;
    }
    /**
     * <code>.services.RequestType request_type = 7;</code>
     * @return The requestType.
     */
    @java.lang.Override public services.Magazinep.RequestType getRequestType() {
      services.Magazinep.RequestType result = services.Magazinep.RequestType.forNumber(requestType_);
      return result == null ? services.Magazinep.RequestType.UNRECOGNIZED : result;
    }

    public static final int OBSERVERS_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private java.util.List<services.Magazinep.User> observers_;
    /**
     * <code>repeated .services.User observers = 8;</code>
     */
    @java.lang.Override
    public java.util.List<services.Magazinep.User> getObserversList() {
      return observers_;
    }
    /**
     * <code>repeated .services.User observers = 8;</code>
     */
    @java.lang.Override
    public java.util.List<? extends services.Magazinep.UserOrBuilder> 
        getObserversOrBuilderList() {
      return observers_;
    }
    /**
     * <code>repeated .services.User observers = 8;</code>
     */
    @java.lang.Override
    public int getObserversCount() {
      return observers_.size();
    }
    /**
     * <code>repeated .services.User observers = 8;</code>
     */
    @java.lang.Override
    public services.Magazinep.User getObservers(int index) {
      return observers_.get(index);
    }
    /**
     * <code>repeated .services.User observers = 8;</code>
     */
    @java.lang.Override
    public services.Magazinep.UserOrBuilder getObserversOrBuilder(
        int index) {
      return observers_.get(index);
    }

    public static final int GENRE_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object genre_ = "";
    /**
     * <code>string genre = 9;</code>
     * @return The genre.
     */
    @java.lang.Override
    public java.lang.String getGenre() {
      java.lang.Object ref = genre_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genre_ = s;
        return s;
      }
    }
    /**
     * <code>string genre = 9;</code>
     * @return The bytes for genre.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGenreBytes() {
      java.lang.Object ref = genre_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(author_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, author_);
      }
      if (borrowed_ != null) {
        output.writeMessage(3, getBorrowed());
      }
      if (returned_ != null) {
        output.writeMessage(4, getReturned());
      }
      if (status_ != services.Magazinep.Status.EXIST.getNumber()) {
        output.writeEnum(5, status_);
      }
      if (type_ != services.Magazinep.Type.MAGAZINE.getNumber()) {
        output.writeEnum(6, type_);
      }
      if (requestType_ != services.Magazinep.RequestType.NONE.getNumber()) {
        output.writeEnum(7, requestType_);
      }
      for (int i = 0; i < observers_.size(); i++) {
        output.writeMessage(8, observers_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(genre_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, genre_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(author_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, author_);
      }
      if (borrowed_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBorrowed());
      }
      if (returned_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getReturned());
      }
      if (status_ != services.Magazinep.Status.EXIST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, status_);
      }
      if (type_ != services.Magazinep.Type.MAGAZINE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_);
      }
      if (requestType_ != services.Magazinep.RequestType.NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, requestType_);
      }
      for (int i = 0; i < observers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, observers_.get(i));
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(genre_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, genre_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof services.Magazinep.Magazine)) {
        return super.equals(obj);
      }
      services.Magazinep.Magazine other = (services.Magazinep.Magazine) obj;

      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getAuthor()
          .equals(other.getAuthor())) return false;
      if (hasBorrowed() != other.hasBorrowed()) return false;
      if (hasBorrowed()) {
        if (!getBorrowed()
            .equals(other.getBorrowed())) return false;
      }
      if (hasReturned() != other.hasReturned()) return false;
      if (hasReturned()) {
        if (!getReturned()
            .equals(other.getReturned())) return false;
      }
      if (status_ != other.status_) return false;
      if (type_ != other.type_) return false;
      if (requestType_ != other.requestType_) return false;
      if (!getObserversList()
          .equals(other.getObserversList())) return false;
      if (!getGenre()
          .equals(other.getGenre())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
      if (hasBorrowed()) {
        hash = (37 * hash) + BORROWED_FIELD_NUMBER;
        hash = (53 * hash) + getBorrowed().hashCode();
      }
      if (hasReturned()) {
        hash = (37 * hash) + RETURNED_FIELD_NUMBER;
        hash = (53 * hash) + getReturned().hashCode();
      }
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + REQUEST_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + requestType_;
      if (getObserversCount() > 0) {
        hash = (37 * hash) + OBSERVERS_FIELD_NUMBER;
        hash = (53 * hash) + getObserversList().hashCode();
      }
      hash = (37 * hash) + GENRE_FIELD_NUMBER;
      hash = (53 * hash) + getGenre().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static services.Magazinep.Magazine parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static services.Magazinep.Magazine parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static services.Magazinep.Magazine parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static services.Magazinep.Magazine parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static services.Magazinep.Magazine parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static services.Magazinep.Magazine parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static services.Magazinep.Magazine parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static services.Magazinep.Magazine parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static services.Magazinep.Magazine parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static services.Magazinep.Magazine parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static services.Magazinep.Magazine parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static services.Magazinep.Magazine parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(services.Magazinep.Magazine prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code services.Magazine}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:services.Magazine)
        services.Magazinep.MagazineOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return services.Magazinep.internal_static_services_Magazine_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return services.Magazinep.internal_static_services_Magazine_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                services.Magazinep.Magazine.class, services.Magazinep.Magazine.Builder.class);
      }

      // Construct using services.Magazinep.Magazine.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        title_ = "";
        author_ = "";
        borrowed_ = null;
        if (borrowedBuilder_ != null) {
          borrowedBuilder_.dispose();
          borrowedBuilder_ = null;
        }
        returned_ = null;
        if (returnedBuilder_ != null) {
          returnedBuilder_.dispose();
          returnedBuilder_ = null;
        }
        status_ = 0;
        type_ = 0;
        requestType_ = 0;
        if (observersBuilder_ == null) {
          observers_ = java.util.Collections.emptyList();
        } else {
          observers_ = null;
          observersBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000080);
        genre_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return services.Magazinep.internal_static_services_Magazine_descriptor;
      }

      @java.lang.Override
      public services.Magazinep.Magazine getDefaultInstanceForType() {
        return services.Magazinep.Magazine.getDefaultInstance();
      }

      @java.lang.Override
      public services.Magazinep.Magazine build() {
        services.Magazinep.Magazine result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public services.Magazinep.Magazine buildPartial() {
        services.Magazinep.Magazine result = new services.Magazinep.Magazine(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(services.Magazinep.Magazine result) {
        if (observersBuilder_ == null) {
          if (((bitField0_ & 0x00000080) != 0)) {
            observers_ = java.util.Collections.unmodifiableList(observers_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.observers_ = observers_;
        } else {
          result.observers_ = observersBuilder_.build();
        }
      }

      private void buildPartial0(services.Magazinep.Magazine result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.title_ = title_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.author_ = author_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.borrowed_ = borrowedBuilder_ == null
              ? borrowed_
              : borrowedBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.returned_ = returnedBuilder_ == null
              ? returned_
              : returnedBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.status_ = status_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.requestType_ = requestType_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.genre_ = genre_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof services.Magazinep.Magazine) {
          return mergeFrom((services.Magazinep.Magazine)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(services.Magazinep.Magazine other) {
        if (other == services.Magazinep.Magazine.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getAuthor().isEmpty()) {
          author_ = other.author_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasBorrowed()) {
          mergeBorrowed(other.getBorrowed());
        }
        if (other.hasReturned()) {
          mergeReturned(other.getReturned());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.requestType_ != 0) {
          setRequestTypeValue(other.getRequestTypeValue());
        }
        if (observersBuilder_ == null) {
          if (!other.observers_.isEmpty()) {
            if (observers_.isEmpty()) {
              observers_ = other.observers_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureObserversIsMutable();
              observers_.addAll(other.observers_);
            }
            onChanged();
          }
        } else {
          if (!other.observers_.isEmpty()) {
            if (observersBuilder_.isEmpty()) {
              observersBuilder_.dispose();
              observersBuilder_ = null;
              observers_ = other.observers_;
              bitField0_ = (bitField0_ & ~0x00000080);
              observersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getObserversFieldBuilder() : null;
            } else {
              observersBuilder_.addAllMessages(other.observers_);
            }
          }
        }
        if (!other.getGenre().isEmpty()) {
          genre_ = other.genre_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                title_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                author_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getBorrowedFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getReturnedFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                requestType_ = input.readEnum();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                services.Magazinep.User m =
                    input.readMessage(
                        services.Magazinep.User.parser(),
                        extensionRegistry);
                if (observersBuilder_ == null) {
                  ensureObserversIsMutable();
                  observers_.add(m);
                } else {
                  observersBuilder_.addMessage(m);
                }
                break;
              } // case 66
              case 74: {
                genre_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        title_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        title_ = getDefaultInstance().getTitle();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        title_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object author_ = "";
      /**
       * <code>string author = 2;</code>
       * @return The author.
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string author = 2;</code>
       * @return The bytes for author.
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string author = 2;</code>
       * @param value The author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        author_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string author = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthor() {
        author_ = getDefaultInstance().getAuthor();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string author = 2;</code>
       * @param value The bytes for author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        author_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp borrowed_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> borrowedBuilder_;
      /**
       * <code>.google.protobuf.Timestamp borrowed = 3;</code>
       * @return Whether the borrowed field is set.
       */
      public boolean hasBorrowed() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp borrowed = 3;</code>
       * @return The borrowed.
       */
      public com.google.protobuf.Timestamp getBorrowed() {
        if (borrowedBuilder_ == null) {
          return borrowed_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : borrowed_;
        } else {
          return borrowedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp borrowed = 3;</code>
       */
      public Builder setBorrowed(com.google.protobuf.Timestamp value) {
        if (borrowedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          borrowed_ = value;
        } else {
          borrowedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp borrowed = 3;</code>
       */
      public Builder setBorrowed(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (borrowedBuilder_ == null) {
          borrowed_ = builderForValue.build();
        } else {
          borrowedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp borrowed = 3;</code>
       */
      public Builder mergeBorrowed(com.google.protobuf.Timestamp value) {
        if (borrowedBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            borrowed_ != null &&
            borrowed_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getBorrowedBuilder().mergeFrom(value);
          } else {
            borrowed_ = value;
          }
        } else {
          borrowedBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp borrowed = 3;</code>
       */
      public Builder clearBorrowed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        borrowed_ = null;
        if (borrowedBuilder_ != null) {
          borrowedBuilder_.dispose();
          borrowedBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp borrowed = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getBorrowedBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getBorrowedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp borrowed = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getBorrowedOrBuilder() {
        if (borrowedBuilder_ != null) {
          return borrowedBuilder_.getMessageOrBuilder();
        } else {
          return borrowed_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : borrowed_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp borrowed = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getBorrowedFieldBuilder() {
        if (borrowedBuilder_ == null) {
          borrowedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getBorrowed(),
                  getParentForChildren(),
                  isClean());
          borrowed_ = null;
        }
        return borrowedBuilder_;
      }

      private com.google.protobuf.Timestamp returned_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> returnedBuilder_;
      /**
       * <code>.google.protobuf.Timestamp returned = 4;</code>
       * @return Whether the returned field is set.
       */
      public boolean hasReturned() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp returned = 4;</code>
       * @return The returned.
       */
      public com.google.protobuf.Timestamp getReturned() {
        if (returnedBuilder_ == null) {
          return returned_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : returned_;
        } else {
          return returnedBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp returned = 4;</code>
       */
      public Builder setReturned(com.google.protobuf.Timestamp value) {
        if (returnedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          returned_ = value;
        } else {
          returnedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp returned = 4;</code>
       */
      public Builder setReturned(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (returnedBuilder_ == null) {
          returned_ = builderForValue.build();
        } else {
          returnedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp returned = 4;</code>
       */
      public Builder mergeReturned(com.google.protobuf.Timestamp value) {
        if (returnedBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            returned_ != null &&
            returned_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getReturnedBuilder().mergeFrom(value);
          } else {
            returned_ = value;
          }
        } else {
          returnedBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp returned = 4;</code>
       */
      public Builder clearReturned() {
        bitField0_ = (bitField0_ & ~0x00000008);
        returned_ = null;
        if (returnedBuilder_ != null) {
          returnedBuilder_.dispose();
          returnedBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp returned = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getReturnedBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getReturnedFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp returned = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getReturnedOrBuilder() {
        if (returnedBuilder_ != null) {
          return returnedBuilder_.getMessageOrBuilder();
        } else {
          return returned_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : returned_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp returned = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getReturnedFieldBuilder() {
        if (returnedBuilder_ == null) {
          returnedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getReturned(),
                  getParentForChildren(),
                  isClean());
          returned_ = null;
        }
        return returnedBuilder_;
      }

      private int status_ = 0;
      /**
       * <code>.services.Status status = 5;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.services.Status status = 5;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.services.Status status = 5;</code>
       * @return The status.
       */
      @java.lang.Override
      public services.Magazinep.Status getStatus() {
        services.Magazinep.Status result = services.Magazinep.Status.forNumber(status_);
        return result == null ? services.Magazinep.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.services.Status status = 5;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(services.Magazinep.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.services.Status status = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000010);
        status_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.services.Type type = 6;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.services.Type type = 6;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>.services.Type type = 6;</code>
       * @return The type.
       */
      @java.lang.Override
      public services.Magazinep.Type getType() {
        services.Magazinep.Type result = services.Magazinep.Type.forNumber(type_);
        return result == null ? services.Magazinep.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.services.Type type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(services.Magazinep.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.services.Type type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = 0;
        onChanged();
        return this;
      }

      private int requestType_ = 0;
      /**
       * <code>.services.RequestType request_type = 7;</code>
       * @return The enum numeric value on the wire for requestType.
       */
      @java.lang.Override public int getRequestTypeValue() {
        return requestType_;
      }
      /**
       * <code>.services.RequestType request_type = 7;</code>
       * @param value The enum numeric value on the wire for requestType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestTypeValue(int value) {
        requestType_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>.services.RequestType request_type = 7;</code>
       * @return The requestType.
       */
      @java.lang.Override
      public services.Magazinep.RequestType getRequestType() {
        services.Magazinep.RequestType result = services.Magazinep.RequestType.forNumber(requestType_);
        return result == null ? services.Magazinep.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.services.RequestType request_type = 7;</code>
       * @param value The requestType to set.
       * @return This builder for chaining.
       */
      public Builder setRequestType(services.Magazinep.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        requestType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.services.RequestType request_type = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestType() {
        bitField0_ = (bitField0_ & ~0x00000040);
        requestType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<services.Magazinep.User> observers_ =
        java.util.Collections.emptyList();
      private void ensureObserversIsMutable() {
        if (!((bitField0_ & 0x00000080) != 0)) {
          observers_ = new java.util.ArrayList<services.Magazinep.User>(observers_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          services.Magazinep.User, services.Magazinep.User.Builder, services.Magazinep.UserOrBuilder> observersBuilder_;

      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public java.util.List<services.Magazinep.User> getObserversList() {
        if (observersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(observers_);
        } else {
          return observersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public int getObserversCount() {
        if (observersBuilder_ == null) {
          return observers_.size();
        } else {
          return observersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public services.Magazinep.User getObservers(int index) {
        if (observersBuilder_ == null) {
          return observers_.get(index);
        } else {
          return observersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public Builder setObservers(
          int index, services.Magazinep.User value) {
        if (observersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObserversIsMutable();
          observers_.set(index, value);
          onChanged();
        } else {
          observersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public Builder setObservers(
          int index, services.Magazinep.User.Builder builderForValue) {
        if (observersBuilder_ == null) {
          ensureObserversIsMutable();
          observers_.set(index, builderForValue.build());
          onChanged();
        } else {
          observersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public Builder addObservers(services.Magazinep.User value) {
        if (observersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObserversIsMutable();
          observers_.add(value);
          onChanged();
        } else {
          observersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public Builder addObservers(
          int index, services.Magazinep.User value) {
        if (observersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObserversIsMutable();
          observers_.add(index, value);
          onChanged();
        } else {
          observersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public Builder addObservers(
          services.Magazinep.User.Builder builderForValue) {
        if (observersBuilder_ == null) {
          ensureObserversIsMutable();
          observers_.add(builderForValue.build());
          onChanged();
        } else {
          observersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public Builder addObservers(
          int index, services.Magazinep.User.Builder builderForValue) {
        if (observersBuilder_ == null) {
          ensureObserversIsMutable();
          observers_.add(index, builderForValue.build());
          onChanged();
        } else {
          observersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public Builder addAllObservers(
          java.lang.Iterable<? extends services.Magazinep.User> values) {
        if (observersBuilder_ == null) {
          ensureObserversIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, observers_);
          onChanged();
        } else {
          observersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public Builder clearObservers() {
        if (observersBuilder_ == null) {
          observers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          observersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public Builder removeObservers(int index) {
        if (observersBuilder_ == null) {
          ensureObserversIsMutable();
          observers_.remove(index);
          onChanged();
        } else {
          observersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public services.Magazinep.User.Builder getObserversBuilder(
          int index) {
        return getObserversFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public services.Magazinep.UserOrBuilder getObserversOrBuilder(
          int index) {
        if (observersBuilder_ == null) {
          return observers_.get(index);  } else {
          return observersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public java.util.List<? extends services.Magazinep.UserOrBuilder> 
           getObserversOrBuilderList() {
        if (observersBuilder_ != null) {
          return observersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(observers_);
        }
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public services.Magazinep.User.Builder addObserversBuilder() {
        return getObserversFieldBuilder().addBuilder(
            services.Magazinep.User.getDefaultInstance());
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public services.Magazinep.User.Builder addObserversBuilder(
          int index) {
        return getObserversFieldBuilder().addBuilder(
            index, services.Magazinep.User.getDefaultInstance());
      }
      /**
       * <code>repeated .services.User observers = 8;</code>
       */
      public java.util.List<services.Magazinep.User.Builder> 
           getObserversBuilderList() {
        return getObserversFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          services.Magazinep.User, services.Magazinep.User.Builder, services.Magazinep.UserOrBuilder> 
          getObserversFieldBuilder() {
        if (observersBuilder_ == null) {
          observersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              services.Magazinep.User, services.Magazinep.User.Builder, services.Magazinep.UserOrBuilder>(
                  observers_,
                  ((bitField0_ & 0x00000080) != 0),
                  getParentForChildren(),
                  isClean());
          observers_ = null;
        }
        return observersBuilder_;
      }

      private java.lang.Object genre_ = "";
      /**
       * <code>string genre = 9;</code>
       * @return The genre.
       */
      public java.lang.String getGenre() {
        java.lang.Object ref = genre_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          genre_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string genre = 9;</code>
       * @return The bytes for genre.
       */
      public com.google.protobuf.ByteString
          getGenreBytes() {
        java.lang.Object ref = genre_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          genre_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string genre = 9;</code>
       * @param value The genre to set.
       * @return This builder for chaining.
       */
      public Builder setGenre(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        genre_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>string genre = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearGenre() {
        genre_ = getDefaultInstance().getGenre();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>string genre = 9;</code>
       * @param value The bytes for genre to set.
       * @return This builder for chaining.
       */
      public Builder setGenreBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        genre_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:services.Magazine)
    }

    // @@protoc_insertion_point(class_scope:services.Magazine)
    private static final services.Magazinep.Magazine DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new services.Magazinep.Magazine();
    }

    public static services.Magazinep.Magazine getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Magazine>
        PARSER = new com.google.protobuf.AbstractParser<Magazine>() {
      @java.lang.Override
      public Magazine parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Magazine> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Magazine> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public services.Magazinep.Magazine getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_services_Magazine_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_services_Magazine_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Magazinep.proto\022\010services\032\037google/prot" +
      "obuf/timestamp.proto\" \n\004User\022\n\n\002id\030\001 \001(\005" +
      "\022\014\n\004name\030\002 \001(\t\"\244\002\n\010Magazine\022\r\n\005title\030\001 \001" +
      "(\t\022\016\n\006author\030\002 \001(\t\022,\n\010borrowed\030\003 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022,\n\010returned\030\004 \001" +
      "(\0132\032.google.protobuf.Timestamp\022 \n\006status" +
      "\030\005 \001(\0162\020.services.Status\022\034\n\004type\030\006 \001(\0162\016" +
      ".services.Type\022+\n\014request_type\030\007 \001(\0162\025.s" +
      "ervices.RequestType\022!\n\tobservers\030\010 \003(\0132\016" +
      ".services.User\022\r\n\005genre\030\t \001(\t*/\n\006Status\022" +
      "\t\n\005EXIST\020\000\022\014\n\010BORROWED\020\001\022\014\n\010RETURNED\020\002*\036" +
      "\n\004Type\022\014\n\010MAGAZINE\020\000\022\010\n\004BOOK\020\001*/\n\013Reques" +
      "tType\022\010\n\004NONE\020\000\022\n\n\006BORROW\020\001\022\n\n\006RETURN\020\002b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_services_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_services_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_User_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_services_Magazine_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_services_Magazine_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_services_Magazine_descriptor,
        new java.lang.String[] { "Title", "Author", "Borrowed", "Returned", "Status", "Type", "RequestType", "Observers", "Genre", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
